create table category
(
    id   bigint generated by default as identity,
    body text
);

alter table ${flyway:defaultSchema}.category
    owner to ${flyway:user};

create table image
(
    id  bigint generated by default as identity
        constraint image_pk primary key,
    alt varchar(255),
    url varchar(255)
);

alter table ${flyway:defaultSchema}.image
    owner to ${flyway:user};

create table producer
(
    id          bigint generated by default as identity
        constraint producer_pk primary key,
    name        varchar(255),
    description text,
    image_url   varchar(255)
);

alter table producer
    owner to ${flyway:user};

create table item_details
(
    id          bigint generated by default as identity
        constraint item_details_pk primary key,
    description text
);

alter table ${flyway:defaultSchema}.item_details
    owner to ${flyway:user};

create table item
(
    id              bigint generated by default as identity
        constraint item_pk primary key,
    name            varchar(255),
    stock           integer          not null check (stock >= 0),
    value_gross     numeric(19, 2),
    vat             double precision not null,
    image_id        bigint
        constraint image_id_fk references image,
    item_details_id bigint
        constraint item_details_fk references item_details,
    producer_id     bigint
        constraint producer_id_fk references producer,
    shipping        bool             not null default false
);

alter table ${flyway:defaultSchema}.item
    owner to ${flyway:user};

create table item_family
(
    id bigint generated by default as identity
        constraint item_family_pk primary key
);

alter table ${flyway:defaultSchema}.item_family
    owner to ${flyway:user};

create table item_family_item
(
    item_id        bigint not null,
    item_family_id bigint not null,
    variant_name   varchar(255),
    constraint item_id_fk foreign key (item_id) references item,
    constraint item_family_pk foreign key (item_family_id) references item_family
);

alter table ${flyway:defaultSchema}.item_family_item
    owner to ${flyway:user};

create table item_category
(
    item_id     bigint not null
        constraint item_id_fk references item,
    category_id uuid   not null
);

alter table ${flyway:defaultSchema}.item_category
    owner to ${flyway:user};

create table item_details_image
(
    item_details_id bigint not null,
    image_id        bigint not null,
    constraint item_details_pk foreign key (item_details_id) references item_details,
    constraint image_uk unique (image_id),
    constraint image_fk foreign key (image_id) references image
);

alter table ${flyway:defaultSchema}.item_details_image
    owner to ${flyway:user};

create table order_details
(
    id                   uuid
        constraint order_details_pk primary key default gen_random_uuid(),
    status               varchar(255),
    payment_method       varchar(255),
    payment_status       varchar(255),
    value_gross          numeric(19, 2) not null,
    value_nett           numeric(19, 2) not null,
    shipping_address_id  uuid,
    user_id              uuid,
    simple_products_json text, -- >> TODO here switch to jsonb later
    created_at           timestamp,
    updated_at           timestamp
);

alter table ${flyway:defaultSchema}.order_details
    owner to ${flyway:user};

create sequence hibernate_sequence start 1 increment 1;

