package com.example.javaopencommerce;

import io.quarkus.runtime.Quarkus;
import io.quarkus.runtime.annotations.QuarkusMain;
import lombok.extern.slf4j.Slf4j;

import java.util.Arrays;
import java.util.Locale;

/**
 * This file is not necessary. It's here, only to act as a starting point for IDE to run project.
 * If this file does not exist, the same (without log statement) will be generated by Quarkus.
 */
@Slf4j
@QuarkusMain
public class QuarkusApp {

    public static void main(String... args) throws InstantiationException {
        log.info("Running quarkus application with parameters: {}", Arrays.asList(args));

        //TODO FIX!
//        if (UnixUtil.runningPrivilegedUser()) {
//            throw new InstantiationException("This application cannot be run as a superuser (root) for security reasons.");
//        }
        Quarkus.run(args);
    }

//    private static class UnixUtil {
//        private static final long UID = 0L;
//        private static final String ROOT = "root";
//
//        static boolean runningPrivilegedUser() {
//            return isUnix() && (isPrivilegedUser() || isPrivilegedGroup() || ROOT.equalsIgnoreCase(System.getProperty("user.name", "undefined")));
//        }
//
//        static boolean isPrivilegedGroup() {
//            return UID == jdk.internal.misc.VM.getgid();
//        }
//        static boolean isPrivilegedUser() {
//            return UID == jdk.internal.misc.VM.geteuid();
//        }
//
//        static boolean isUnix() {
//            String os = System.getProperty("os.name", "undefined").toLowerCase(Locale.ROOT);
//            return os.contains("nux") || os.contains("mac");
//        }
//    }
}