create table item_producer
(
	item_id bigint not null,
	producer_id bigint not null,
	constraint item_producer_pkey
		primary key (item_id, producer_id)
);

alter table item_producer owner to testuser;

create table category
(
	id bigint generated by default as identity
		constraint category_pkey
			primary key
);

alter table category owner to testuser;

create table categorydetails
(
	id bigint generated by default as identity
		constraint categorydetails_pkey
			primary key,
	description varchar(255),
	lang varchar(255),
	name varchar(255),
	category_id bigint
		constraint fkq814ig8rkfqav40q4l43qc6yp
			references category
);

alter table categorydetails owner to testuser;

create table image
(
	id bigint generated by default as identity
		constraint image_pkey
			primary key,
	alt varchar(255),
	url varchar(255)
);

alter table image owner to testuser;

create table producer
(
	id bigint generated by default as identity
		constraint producer_pkey
			primary key,
	image_id bigint
		constraint fkbys83yrqd6lk532iw50bkolj4
			references image
);

alter table producer owner to testuser;

create table item
(
	id bigint generated by default as identity
		constraint item_pkey
			primary key,
	stock integer not null,
	valuegross numeric(19,2),
	vat double precision not null,
	image_id bigint
		constraint fkr3q9b86cnpfnveexfr4iaefrg
			references image,
	producer_id bigint
		constraint fkjomcd7hhvl6l36mgb4rwa01w5
			references producer
);

alter table item owner to testuser;

create table item_category
(
	item_id bigint not null
		constraint fklqjc8u9wq0w59oqhw60dw86s5
			references item,
	category_id bigint not null
		constraint fkb00nakmw9p95imf42fpu3948y
			references category,
	constraint item_category_pkey
		primary key (item_id, category_id)
);

alter table item_category owner to testuser;

create table itemdetails
(
	id bigint generated by default as identity
		constraint itemdetails_pkey
			primary key,
	description text,
	lang varchar(255),
	name varchar(255),
	item_id bigint
		constraint fkmj7i7pip4krc7dhch8idowlnc
			references item
);

alter table itemdetails owner to testuser;

create table itemdetails_image
(
	itemdetails_id bigint not null
		constraint fkcqpkvkjurqbq34ieh7f49bwvo
			references itemdetails,
	images_id bigint not null
		constraint uk_d2y1g5igcxbitt9wso7t98j13
			unique
		constraint fkskce1wx21du16cedbhf3jlohf
			references image,
	constraint itemdetails_image_pkey
		primary key (itemdetails_id, images_id)
);

alter table itemdetails_image owner to testuser;

create table producerdetails
(
	id bigint generated by default as identity
		constraint producerdetails_pkey
			primary key,
	description varchar(255),
	lang varchar(255),
	name varchar(255),
	producer_id bigint
		constraint fkp0lw3c0vlnxmjihsnsv7h0hte
			references producer
);

alter table producerdetails owner to testuser;

create table userentity
(
	id bigint generated by default as identity
		constraint userentity_pkey
			primary key,
	email varchar(255),
	firstname varchar(255),
	lastname varchar(255)
);

alter table userentity owner to testuser;

create table address
(
	id bigint generated by default as identity
		constraint address_pkey
			primary key,
	city varchar(255),
	local varchar(255),
	street varchar(255),
	zip varchar(255),
	user_id bigint
		constraint fk7xwr01ggh9t1nudtn7nyeiq17
			references userentity
);

alter table address owner to testuser;

create table orderdetails
(
	id bigint generated by default as identity
		constraint orderdetails_pkey
			primary key,
	creationdate date,
	orderstatus varchar(255),
	paymentmethod varchar(255),
	paymentstatus varchar(255),
	address_id bigint
		constraint fk73i6yle3sw7byge9vdc5l991d
			references address,
	userentity_id bigint
		constraint fk9apxoaew427qtq01af4e974j2
			references userentity,
    orderdetails jsonb
);

alter table orderdetails owner to testuser;

create table userentity_permissions
(
	userentity_id bigint not null
		constraint fklq8nprkjk8ryvmvvdmf1dh6ji
			references userentity,
	permissions varchar(255)
);

alter table userentity_permissions owner to testuser;

-- SEQUENCES ---------------------------------------------------

alter sequence item_id_seq
    increment by 1
    minvalue 20
    start 20
    restart 20;
alter sequence item_id_seq owner to testuser;



