version: '3'

services:
  postgresql:
    image: postgres:13.1
    ports:
      - "5432:5432"
    ulimits:
      memlock: -1
    restart: always
    environment:
      - POSTGRES_DB=main_postgres_db
      - POSTGRES_USER=${QUARKUS_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
    networks:
      - com-example-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - com-example-network

  redis:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - com-example-network

networks:
  com-example-network:
